backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "equipos"
    label: "Equipos"
    folder: "equipos"
    create: true
    fields:
      - {label: "Nombre", name: "title", widget: "string"}
      - {label: "Descripción", name: "body", widget: "text"}
      - {label: "Imagen", name: "image", widget: "image"}

  - name: "resultados"
    label: "Resultados"
    folder: "resultados"
    create: true
    fields:
      - {label: "Partido", name: "title", widget: "string"}
      - {label: "Marcador", name: "body", widget: "text"}
